name: Deploy Shorebird Patch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      - name: Deploy Android Patch
        run: shorebird patch android --release-version=latest
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
